apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-consumer-perf
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: redpanda-consumer-perf
    spec:
      containers:
        - name: redpanda-consumer-perf
          image: docker.artifactory.dhl.com/osp/redpanda-perf-tools:latest
          imagePullPolicy: Always
          env:
            - name: DEBUG_CONTAINER_MODE
              value: kafka-consumer-perf-test
          envFrom:
            - configMapRef:
                name: redpanda-consumer-configs
          volumeMounts:
            - mountPath: /etc/redpanda/configs
              name: osp-redpanda-consumer-props
              readOnly: true
            - mountPath: /etc/certs
              name: osp-redpanda-perf-certs
              readOnly: true
      imagePullSecrets:
        - name: osp-redpanda-regcred
      volumes:
        - name: osp-redpanda-consumer-props
          secret:
            defaultMode: 420
            items:
              - key: redpanda.properties
                path: redpanda.properties
            secretName: osp-redpanda-props
        - name: osp-redpanda-perf-certs
          secret:
            defaultMode: 420
            items:
              - key: keystore.jks
                path: keystore.jks
              - key: truststore.jks
                path: truststore.jks
            secretName: osp-redpanda-perf-certs
      hostAliases:
        - hostnames:
            - "osp-redpanda-0.osp-redpanda.osp-redpanda.svc.cluster.local"
          ip: "165.72.89.68"
        - hostnames:
            - "osp-redpanda-1.osp-redpanda.osp-redpanda.svc.cluster.local"
          ip: "165.72.89.67"
        - hostnames:
            - "osp-redpanda-2.osp-redpanda.osp-redpanda.svc.cluster.local"
          ip: "165.72.89.66"
  selector:
    matchLabels:
      deployment: redpanda-consumer-perf