apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: osp-rpk-perftest

resources:
  - producer-deployment.yaml
  - consumer-deployment.yaml
  - secrets/rpk-properties-Secrets-sealed.yaml
  - secrets/rpk-certstore-Secrets-sealed.yaml
  - secrets/rpk-regcred-Secrets-sealed.yaml

configMapGenerator:
  - name: redpanda-producer-configs
    behavior: create
    envs:
      - producer_perf_test.env
  - name: redpanda-consumer-configs
    behavior: create
    envs:
      - consumer_perf_test.env
#secretGenerator:
##  - name: osp-redpanda-producer-props
##    behavior: create
##    files:
##      - redpanda-producer.properties
#  - name: osp-redpanda-certstore
#    behavior: create
#    files:
#      - certs/cluster.keystore.jks
#      - certs/cluster.truststore.jks