---
############### console admin values ###############
admin:
  image:
    registry: "docker.artifactory.dhl.com"
    tag: "v2.2.3"
  configmap:
    create: false
  secret:
    create: false
  deployment:
    create: true
  #  secretMounts:
  #    - name: certs
  #      secretName: osp-redpanda-default-cert
  #      path: /etc/tls/certs/default/
  #      defaultMode: 0600
  extraEnvFrom:
    - secretRef:
        name: osp-redpanda-console-admin
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: osp-redpanda-console-admin-basicauth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - ospredpanda'
    enabled: true
    hosts:
      - host: osp-redpanda-admin.apps-odfe.datalake-dev.dhl.com
        paths:
          - path: /
            pathType: ImplementationSpecific

############### console client values ###############
client:
  image:
    registry: "docker.artifactory.dhl.com"
    tag: "v2.2.3"
  configmap:
    create: false
  secret:
    create: false
  deployment:
    create: true
  #  secretMounts:
  #    - name: certs
  #      secretName: osp-redpanda-default-cert
  #      path: /etc/tls/certs/default/
  #      defaultMode: 0600
  extraEnvFrom:
    - secretRef:
        name: osp-redpanda-console-client
  ingress:
    enabled: true
    hosts:
      - host: osp-redpanda-client.apps-odfe.datalake-dev.dhl.com
        paths:
          - path: /
            pathType: ImplementationSpecific

############### Kminion values ###############
kminion:
  image:
    repository: vectorized/kminion
    tag: "v2.2.4"
  nameOverride: "osp-redpanda-kminion"
  fullnameOverride: "osp-redpanda-kminion"
  ingress:
    enabled: true
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - osp-redpanda-kminion.apps-odfe.datalake-dev.dhl.com
    path: /
    pathType: ImplementationSpecific
    tls: []

  serviceMonitor:
    create: true

  deployment:
#    volumes:
#    # Mount files from Kubernetes secrets into the container
#        secrets:
#          - name: certs
#            secretName: osp-redpanda-default-cert
#            mountPath: /etc/tls/certs/default/
    env:
      secretKeyRefs:
        - name: KAFKA_SASL_PASSWORD
          secretName: osp-redpanda-kminion-cred
          secretKey: password