{{/*apiVersion: v1*/}}
{{/*kind: ConfigMap*/}}
{{/*metadata:*/}}
{{/*  name: oss-its-gsd-opensearch-master*/}}
{{/*data:*/}}
{{/*{{ (.Files.Glob "references/opensearchConfig/*").AsConfig | indent 2 }}*/}}

{{/*---*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: its-gsd-opensearch-dashboards-config
data:
{{ (.Files.Glob "references/dashboards/*").AsConfig | indent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: oss-its-gsd-opensearch-master-securityconfig
type: Opaque
data:
{{ (.Files.Glob "references/securityconfig/*").AsSecrets | indent 2 }}