{{- range tuple "0" "1" "2" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oss-its-gsd-opensearch-{{ . }}
  labels:
    name: oss-its-gsd-opensearch-{{ . }}
    namespace: oss-its-gsd-opensearch
spec:
  storageClassName: maprfs-fuse-storage
  claimRef:
    name: oss-its-gsd-opensearch-master-oss-its-gsd-opensearch-master-{{ . }}
    namespace: oss-its-gsd-opensearch
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Gi
  csi:
    nodePublishSecretRef:
      name: oss-its-gsd-opensearch-mapr
      namespace: oss-its-gsd-opensearch
    driver: com.mapr.csi-kdf
    volumeHandle: maprfs-pv-oss-its-gsd-opensearch
    volumeAttributes:
      volumePath: "/oss-its-gsd-opensearch-{{ . }}"
      cldbHosts: czchols4222.prg-dc.dhl.com czchols4223.prg-dc.dhl.com czchols4224.prg-dc.dhl.com
      cluster: datalake-dev.dhl.com
      securityType: "secure"
---
{{- end }}
