apiVersion: v2
name: oss-thanos
description: A Helm chart for thanos
type: application
version: 0.1.0
appVersion: "12.0.6"

dependencies:
  - name: thanos
    repository: https://charts.bitnami.com/bitnami
    version: 12.0.6
