---
scylla-operator:
  replicas: 2

  # Scylla Operator log level, 0-9 (higher number means more detailed logs)
  logLevel: 2
  # Resources allocated to Scylla Operator pods
  resources:
    requests:
      cpu: 500m
      memory: 100Mi

  webhook:
    createSelfSignedCertificate: true

  serviceAccount:
    create: true

  webhookServerReplicas: 2
