apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-monitoring-admin
data:
{{ (.Files.Glob "references/admin/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-monitoring-client
data:
{{ (.Files.Glob "references/client/*").AsConfig | indent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: osp-redpanda-kminion
data:
{{ (.Files.Glob "references/kminion/*").AsConfig | indent 2 }}
