apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-oss
  namespace: argocd
spec:
  description: >-
    Applications and other manifests deployed on the **dev-oss** cluster.

  destinations:
  - name: 'dev-oss'
    namespace: '*'
    server: https://kubernetes.default.svc

  sourceRepos:
  - https://git.dhl.com/DATA-LAKE-10108/oss-gitops

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  orphanedResources:
    warn: false
