---
manage_snapshots:
  hosts: []
  users: []
  reserved: false
  hidden: false
  backend_roles:
    - "snapshotrestore"
  and_backend_roles: []
logstash:
  hosts: []
  users: []
  reserved: false
  hidden: false
  backend_roles:
    - "logstash"
  and_backend_roles: []
own_index:
  hosts: []
  users:
    - "*"
  reserved: false
  hidden: false
  backend_roles: []
  and_backend_roles: []
  description: "Allow full access to an index named like the username"
kibana_user:
  hosts: []
  users: []
  reserved: false
  hidden: false
  backend_roles:
    - "kibanauser"
  and_backend_roles: []
  description: "Maps kibanauser to kibana_user"
_meta:
  type: "rolesmapping"
  config_version: 2
all_access:
  hosts: []
  users:
    - "clkocp"
  reserved: false
  hidden: false
  backend_roles:
    - "admin"
    - "udldhl-dl-xdiv-app-logging-system-m-rwx"
    - "udldhl-oss-admins"
  and_backend_roles: []
cluster_monitor:
  hosts: []
  users:
    - "srv_data-lake-topaz"
  reserved: false
  hidden: false
  backend_roles: []
  and_backend_roles: []
its_gsd_role_service_account:
  hosts: []
  users:
    - "itsgsd"
  reserved: false
  hidden: false
  backend_roles: []
  and_backend_roles: []
readall:
  hosts: []
  users: []
  reserved: false
  hidden: false
  backend_roles:
    - "readall"
  and_backend_roles: []
kibana_server:
  hosts: []
  users:
    - "kibanaserver"
  reserved: true
  hidden: false
  backend_roles: []
  and_backend_roles: []
its_gsd_role:
  hosts: []
  users: []
  reserved: false
  hidden: false
  backend_roles:
    - "UAPCZITS-GSD-OpenSearch-dev-admin"
  and_backend_roles: []