{{/*apiVersion: bitnami.com/v1alpha1*/}}
{{/*kind: SealedSecret*/}}
{{/*metadata:*/}}
{{/*  creationTimestamp: null*/}}
{{/*  name: osp-redpanda-mapr*/}}
{{/*  namespace: osp-redpanda*/}}
{{/*spec:*/}}
{{/*  encryptedData:*/}}
{{/*    CONTAINER_TICKET: AgC0b5XEk23bSHFJ6kEbKb5zfZUsRvd/1t26MpmVBnRcf8uIlxzQmAzha6BPW7GTG78lsZMDEVk5urMrMjPo3OPjZu0fdckK17Bl6z5thAMUYUE2dof6fFRTtMPv/l/B8yt4PsNugLOB948uUXcudc6TyExqr2vpI2S/9llP6sx4SklBX/Z+4am9pxaRA1cVYIiY0A10mnoe9a/68qFVbpsZVD3WChaUr9d86GbDgFxTDP1ejvQxNqewwj0x6kkSLKYoVfBjPoIvJhvez7IdapAKobqUnwMShDFjqw7l9YbWPmYfaYRebB+xJTvyKBNIRoq7cobh3E9E5JfpiulueNTzm9XfIQ3xjFyiFiWblsrPP7PqUaH6qZCj552D1FxSncaL2rE4+dL1hU+dcOvvBcpf9JyMz3E4jm6gVv6OeKUuOMdIwHpc/RXdx5zkdgUJ2e2yRsEqslogByPlSN0/GQMMd2e2nExgzNTMu6CymtkY+8y6TZmUlIYItrUAuJUdf9u2Y8v2kYVQpJ97NutHuQJDg4DtVlyF1JlyuNQcntqL4gWyCt4FnSyF8Thf0DAVevAlbvbcF3i9FD5t+5JzAFTHaq2GCpQGQ96clbv6EEBYQopTJ3VWtGqmvi/LFaH5lqegQpIXL+ZIM84WdG8AFQrcPcrqN2iqiJzZRKHEK698AkCwOEFBurqr4+QQtHcsANw7aPmc8LmD4hnILaolybNSOlu+1evnnpmMEeAliLf8xRg0ASeaQvqs1Ci3A9Q0bsaaRqv/TDrrZ/r3mqc3ey2r+A/It4GjP0HV3btY/VnCTuZk7JhsnN/noH8YV927wMCljzdS4CC/YUyUjnuIWPtIg9/dZ8Ib1/5ItGH2XunK1VUKzSaGqASrk9u3+uWfiVKfN97+KLpo67H0i9nV6n+ydtL31qpoIJPByxV50aBPrTBprihtbb1vG3iOImCfPPDpUyGRVmMZMXdRkF0l+GbVVcqpQjDR8GDE5dc74/Vmyq+/tgGHxP3d+LX4LntlzUKPU+ZFhsRTZ1dkD4xaxBJCWUmoZ/CGcvotfApp2rtmTX+2E3fqLaGgyN2MU4k25qZlb4x112Qka65zCVE9kUW7VnOAnwC42a8vGP1weib5P9FjkpfkVRyCQJA=*/}}
{{/*  template:*/}}
{{/*    metadata:*/}}
{{/*      creationTimestamp: null*/}}
{{/*      name: osp-redpanda-mapr*/}}
{{/*      namespace: osp-redpanda*/}}
{{/*    type: Opaque*/}}

