---
_meta:
  type: "config"
  config_version: 2
config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authc:
      internal_auth:
        order: 0
        description: "HTTP basic authentication using the internal user database"
        http_enabled: true
        transport_enabled: true
        http_authenticator:
          type: "basic"
          challenge: false
        authentication_backend:
          type: "internal"
      ldap_auth:
        order: 1
        description: "Authenticate using LDAP"
        http_enabled: true
        transport_enabled: true
        http_authenticator:
          type: "basic"
          challenge: false
        authentication_backend:
          type: "ldap"
          config:
            enable_ssl: false
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: true
            hosts:
              - "dhl.com:3268"
            bind_dn: "${env.LDAP_BIND_DN}"
            password: "${env.LDAP_BIND_PASSWORD}"
            userbase: "dc=dhl,dc=com"
            usersearch: "(|(sAMAccountName={0})(userPrincipalName={0}))"
            username_attribute: "sAMAccountName"
    authz:
      ldap_roles:
        description: "Authorize using LDAP"
        http_enabled: true
        transport_enabled: true
        authorization_backend:
          type: "ldap"
          config:
            enable_ssl: false
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: true
            hosts:
              - "dhl.com:3268"
            bind_dn: "${env.LDAP_BIND_DN}"
            password: "${env.LDAP_BIND_PASSWORD}"
            userbase: "dc=dhl,dc=com"
            usersearch: "(|(sAMAccountName={0})(userPrincipalName={0}))"
            username_attribute: "sAMAccountName"
            skip_users:
              - "admin"
              - "kibanaserver"
            rolebase: "dc=dhl,dc=com"
            rolesearch: "(uniqueMember={0})"
            userroleattribute: null
            userrolename: "memberOf"
            rolename: "cn"
            resolve_nested_roles: false