---
asynchronous_search_read_access:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:admin/opendistro/asynchronous_search/get"
  index_permissions: []
  tenant_permissions: []
  static: false
kibana_read_only:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions: []
  tenant_permissions: []
  static: false
alerting_full_access:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster_monitor"
    - "cluster:admin/opendistro/alerting/*"
  index_permissions:
    - index_patterns:
        - "*"
      fls: []
      masked_fields: []
      allowed_actions:
        - "indices_monitor"
        - "indices:admin/aliases/get"
        - "indices:admin/mappings/get"
  tenant_permissions: []
  static: false
_meta:
  type: "roles"
  config_version: 2
reports_read_access:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:admin/opendistro/reports/definition/get"
    - "cluster:admin/opendistro/reports/definition/list"
    - "cluster:admin/opendistro/reports/instance/list"
    - "cluster:admin/opendistro/reports/instance/get"
    - "cluster:admin/opendistro/reports/menu/download"
  index_permissions: []
  tenant_permissions: []
  static: false
its_gsd_role_service_account:
  reserved: false
  hidden: false
  cluster_permissions:
    - "cluster_composite_ops"
    - "cluster_monitor"
    - "indices:data/read/get"
    - "indices:admin/analyze"
    - "indices:admin/template/put"
    - "indices:admin/template/get"
    - "indices:data/read/scroll/clear"
    - "indices:admin/aliases/get"
    - "indices:admin/create"
  index_permissions:
    - index_patterns:
        - "its-gsd-*"
      dls: ""
      fls: []
      masked_fields: []
      allowed_actions:
        - "indices_all"
        - "indices:admin/analyze"
  tenant_permissions:
    - tenant_patterns:
        - "its_gsd_tenant"
      allowed_actions:
        - "kibana_all_write"
  static: false
anomaly_read_access:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:admin/opendistro/ad/detector/info"
    - "cluster:admin/opendistro/ad/detector/search"
    - "cluster:admin/opendistro/ad/detectors/get"
    - "cluster:admin/opendistro/ad/result/search"
    - "cluster:admin/opendistro/ad/tasks/search"
  index_permissions: []
  tenant_permissions: []
  static: false
anomaly_full_access:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster_monitor"
    - "cluster:admin/opendistro/ad/*"
  index_permissions:
    - index_patterns:
        - "*"
      fls: []
      masked_fields: []
      allowed_actions:
        - "indices_monitor"
        - "indices:admin/aliases/get"
        - "indices:admin/mappings/get"
  tenant_permissions: []
  static: false
alerting_read_access:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:admin/opendistro/alerting/alerts/get"
    - "cluster:admin/opendistro/alerting/destination/get"
    - "cluster:admin/opendistro/alerting/monitor/get"
    - "cluster:admin/opendistro/alerting/monitor/search"
  index_permissions: []
  tenant_permissions: []
  static: false
reports_instances_read_access:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:admin/opendistro/reports/instance/list"
    - "cluster:admin/opendistro/reports/instance/get"
    - "cluster:admin/opendistro/reports/menu/download"
  index_permissions: []
  tenant_permissions: []
  static: false
its_gsd_role:
  reserved: false
  hidden: false
  cluster_permissions:
    - "cluster_composite_ops"
    - "cluster_monitor"
    - "indices:data/read/get"
  index_permissions:
    - index_patterns:
        - "its-gsd-*"
      dls: ""
      fls: []
      masked_fields: []
      allowed_actions:
        - "read"
        - "create_index"
  tenant_permissions:
    - tenant_patterns:
        - "its_gsd_tenant"
      allowed_actions:
        - "kibana_all_write"
  static: false
asynchronous_search_full_access:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:admin/opendistro/asynchronous_search/*"
  index_permissions:
    - index_patterns:
        - "*"
      fls: []
      masked_fields: []
      allowed_actions:
        - "indices:data/read/search*"
  tenant_permissions: []
  static: false
reports_full_access:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:admin/opendistro/reports/definition/create"
    - "cluster:admin/opendistro/reports/definition/update"
    - "cluster:admin/opendistro/reports/definition/on_demand"
    - "cluster:admin/opendistro/reports/definition/delete"
    - "cluster:admin/opendistro/reports/definition/get"
    - "cluster:admin/opendistro/reports/definition/list"
    - "cluster:admin/opendistro/reports/instance/list"
    - "cluster:admin/opendistro/reports/instance/get"
    - "cluster:admin/opendistro/reports/menu/download"
  index_permissions: []
  tenant_permissions: []
  static: false
security_rest_api_access:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions: []
  tenant_permissions: []
  static: false
alerting_ack_alerts:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:admin/opendistro/alerting/alerts/*"
  index_permissions: []
  tenant_permissions: []
  static: false
cluster_monitor:
  reserved: false
  hidden: false
  cluster_permissions:
    - "cluster_monitor"
  index_permissions: []
  tenant_permissions: []
  static: false
notebooks_read_access:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:admin/opendistro/notebooks/list"
    - "cluster:admin/opendistro/notebooks/get"
  index_permissions: []
  tenant_permissions: []
  static: false
notebooks_full_access:
  reserved: true
  hidden: false
  cluster_permissions:
    - "cluster:admin/opendistro/notebooks/create"
    - "cluster:admin/opendistro/notebooks/update"
    - "cluster:admin/opendistro/notebooks/delete"
    - "cluster:admin/opendistro/notebooks/get"
    - "cluster:admin/opendistro/notebooks/list"
  index_permissions: []
  tenant_permissions: []
  static: false