cluster.name: oss-its-gsd
action.auto_create_index: false

# Bind to all interfaces because we don't know what IP address Docker will assign to us.
network.host: 0.0.0.0

# Setting network.host to a non-loopback address enables the annoying bootstrap checks. "Single-node" mode disables them again.
# discovery.type: single-node

http:
  max_content_length: 200mb

# Start OpenSearch Security Demo Configuration
# WARNING: revise all the lines below before you go into production
plugins:
  security:
    disabled: false
    ssl:
      transport:
        pemcert_filepath: certs/node1.pem
        pemkey_filepath: certs/node1-key.pem
        pemtrustedcas_filepath: certs/root-ca.pem
        enforce_hostname_verification: false
      http:
        enabled: true
        pemcert_filepath: certs/node1.pem
        pemkey_filepath: certs/node1-key.pem
        pemtrustedcas_filepath: certs/root-ca.pem
    allow_unsafe_democertificates: false
    allow_default_init_securityindex: true
    authcz:
      admin_dn:
        - CN=A,OU=OSS,O=DHL,L=PRG,ST=PRG,C=CZ
    nodes_dn:
      - CN=oss-its-gsd-opensearch.svc.cluster.local,OU=OSS,O=DHL,L=PRG,ST=PRG,C=CZ

    audit.type: internal_opensearch
    enable_snapshot_restore_privilege: true
    check_snapshot_restore_write_privileges: true
    restapi:
      roles_enabled: ["all_access", "security_rest_api_access"]
    system_indices:
      enabled: true
      indices:
        [
          ".opendistro-alerting-config",
          ".opendistro-alerting-alert*",
          ".opendistro-anomaly-results*",
          ".opendistro-anomaly-detector*",
          ".opendistro-anomaly-checkpoints",
          ".opendistro-anomaly-detection-state",
          ".opendistro-reports-*",
          ".opendistro-notifications-*",
          ".opendistro-notebooks",
          ".opendistro-asynchronous-search-response*",
        ]