---
############### redpanda cluster values ###############
redpanda:
  image:
    tag: "v23.1.8"
  nameOverride: "osp-redpanda"
  fullnameOverride: "osp-redpanda"
  auth:
    sasl:
      enabled: true
      mechanism: SCRAM-SHA-512
      secretRef: "osp-redpanda-users"
      users: []
  tls:
    enabled: false
    certs:
      default:
        caEnabled: false
  post_install_job:
    enabled: true
  post_upgrade_job:
    enabled: true

  storage:
    persistentVolume:
      enabled: true
      storageClass: "longhorn-nvme"
      size: 2048Gi

  tuning:
    tune_clocksource: true
    tune_ballast_file: true
    ballast_file_path: "/var/lib/redpanda/data/ballast"
    ballast_file_size: "1GiB"

  config:
    cluster:
      auto_create_topics_enabled: false                             # Allow topic auto creation
      transaction_coordinator_replication: 3                      # Replication factor for a transaction coordinator topic
      id_allocator_replication: 3                                  # Replication factor for an ID allocator topic
      enable_idempotence: true                                    # Enable idempotent producer
      enable_transactions: true                                   # Enable transactions
    node:
      developer_mode: false                                     # Skips most of the checks performed at startup
  console:
    enabled: false

  resources:
    cpu:
      cores: 8
    memory:
      enable_memory_locking: true
      container:
        min: 40Gi
        max: 40Gi

  # External access configuration
  external:
    enabled: true
    type: NodePort
    addresses:
    - 165.72.114.69
    - 165.72.114.68
    - 165.72.114.67
